[supervisord]
nodaemon=true

[program:django]
command=/bin/bash -c "python3 tutors_django/manage.py makemigrations && python3 tutors_django/manage.py migrate && python3 tutors_django/manage.py runserver 0.0.0.0:8000"
#command=python tutors_django/manage.py runserver 0.0.0.0:8000
autostart=true
autorestart=true
# stdout_logfile=/dev/stdout
# stderr_logfile=/dev/stderr

[program:daphne]
command=daphne -b 0.0.0.0 -p 8001 tutors_django.config.asgi:application
autostart=true
autorestart=true
# stdout_logfile=/dev/stdout
# stderr_logfile=/dev/stderr
