export const HanWords = [
    {"#": 1, "Hanzi": "人们", "Pinyin": "rén men", "English": "people"},
    {"#": 2, "Hanzi": "是的", "Pinyin": "shì de", "English": "yes"},
    {"#": 3, "Hanzi": "不是", "Pinyin": "bú shì", "English": "no; not"},
    {"#": 4, "Hanzi": "人的", "Pinyin": "rén de", "English": "person's"},
    {"#": 5, "Hanzi": "我的", "Pinyin": "wǒ de", "English": "my; mine"},
    {"#": 6, "Hanzi": "不在", "Pinyin": "bú zài", "English": "not here"},
    {"#": 7, "Hanzi": "有了", "Pinyin": "yǒu le", "English": "have; got"},
    {"#": 8, "Hanzi": "有的", "Pinyin": "yǒu de", "English": "some"},
    {"#": 9, "Hanzi": "他的", "Pinyin": "tā de", "English": "his"},
    {"#": 10, "Hanzi": "他人", "Pinyin": "tā rén", "English": "others"},
    {"#": 11, "Hanzi": "来了", "Pinyin": "lái le", "English": "came"},
    {"#": 12, "Hanzi": "个人", "Pinyin": "gè rén", "English": "individual"},
    {"#": 13, "Hanzi": "人中", "Pinyin": "rén zhōng", "English": "among people"},
    {"#": 14, "Hanzi": "不上", "Pinyin": "bú shàng", "English": "cannot go up"},
    {"#": 15, "Hanzi": "他们", "Pinyin": "tā men", "English": "they"},
    {"#": 16, "Hanzi": "他们的", "Pinyin": "tā men de", "English": "their; theirs"},
    {"#": 17, "Hanzi": "我们", "Pinyin": "wǒ men", "English": "we; us"},
    {"#": 18, "Hanzi": "我们的", "Pinyin": "wǒ men de", "English": "our; ours"},
    {"#": 19, "Hanzi": "人们的", "Pinyin": "rén men de", "English": "people's"},
    {"#": 20, "Hanzi": "说到", "Pinyin": "shuō dào", "English": "talking about"},
    {"#": 21, "Hanzi": "我来说", "Pinyin": "wǒ lái shuō", "English": "let me say"},
    {"#": 22, "Hanzi": "他来说", "Pinyin": "tā lái shuō", "English": "let him say"},
    {"#": 23, "Hanzi": "她的", "Pinyin": "tā de", "English": "her; hers"},
    {"#": 24, "Hanzi": "她们", "Pinyin": "tā men", "English": "they (females)"},
    {"#": 25, "Hanzi": "她们的", "Pinyin": "tā men de", "English": "their (females)"},
    {"#": 26, "Hanzi": "他来说", "Pinyin": "tā lái shuō", "English": "let him talk"},
    {"#": 27, "Hanzi": "到了", "Pinyin": "dào le", "English": "arrived"},
    {"#": 28, "Hanzi": "到家了", "Pinyin": "dào jiā le", "English": "arrived home"},
    {"#": 29, "Hanzi": "中国", "Pinyin": "zhōng guó", "English": "China"},
    {"#": 30, "Hanzi": "中国人", "Pinyin": "zhōng guó rén", "English": "Chinese person"},
    {"#": 31, "Hanzi": "到中国", "Pinyin": "dào zhōng guó", "English": "to China"},
    {"#": 32, "Hanzi": "到国", "Pinyin": "dào guó", "English": "to the country"},
    {"#": 33, "Hanzi": "土地", "Pinyin": "tǔ dì", "English": "land"},
    {"#": 34, "Hanzi": "国土", "Pinyin": "guó tǔ", "English": "territory"},
    {"#": 35, "Hanzi": "好地", "Pinyin": "hǎo dì", "English": "good place"},
    {"#": 36, "Hanzi": "出国", "Pinyin": "chū guó", "English": "go abroad"},
    {"#": 37, "Hanzi": "我子", "Pinyin": "wǒ zǐ", "English": "my child"},
    {"#": 38, "Hanzi": "到时", "Pinyin": "dào shí", "English": "at that time"},
    {"#": 39, "Hanzi": "说出", "Pinyin": "shuō chū", "English": "speak out"},
    {"#": 40, "Hanzi": "说出来", "Pinyin": "shuō chū lái", "English": "say it out loud"},
    {"#": 41, "Hanzi": "说不了", "Pinyin": "shuō bù liǎo", "English": "cannot say"},
    {"#": 42, "Hanzi": "说不出来", "Pinyin": "shuō bù chū lái", "English": "cannot express"},
    {"#": 43, "Hanzi": "我要", "Pinyin": "wǒ yào", "English": "I want"},
    {"#": 44, "Hanzi": "我不要", "Pinyin": "wǒ bù yào", "English": "I don't want"},
    {"#": 45, "Hanzi": "要不要", "Pinyin": "yào bù yào", "English": "want or not"},
    {"#": 46, "Hanzi": "好不好", "Pinyin": "hǎo bù hǎo", "English": "good or not"},
    {"#": 47, "Hanzi": "是不是", "Pinyin": "shì bù shì", "English": "is it?"},
    {"#": 48, "Hanzi": "就是", "Pinyin": "jiù shì", "English": "exactly; just"},
    {"#": 49, "Hanzi": "上下", "Pinyin": "shàng xià", "English": "up and down"},
    {"#": 50, "Hanzi": "上来", "Pinyin": "shàng lái", "English": "come up"},
    {"#": 51, "Hanzi": "下来", "Pinyin": "xià lái", "English": "come down"},
    {"#": 52, "Hanzi": "到得", "Pinyin": "dào dé", "English": "arrivable"},
    {"#": 53, "Hanzi": "得到", "Pinyin": "dé dào", "English": "obtain"},
    {"#": 54, "Hanzi": "可是", "Pinyin": "kě shì", "English": "but"},
    {"#": 55, "Hanzi": "你们", "Pinyin": "nǐ men", "English": "you (plural)"},
    {"#": 56, "Hanzi": "你们的", "Pinyin": "nǐ men de", "English": "your; yours (plural)"},
    {"#": 57, "Hanzi": "你们来", "Pinyin": "nǐ men lái", "English": "you come"},
    {"#": 58, "Hanzi": "你们是", "Pinyin": "nǐ men shì", "English": "you are"},
    {"#": 59, "Hanzi": "你们要", "Pinyin": "nǐ men yào", "English": "you want"},
    {"#": 60, "Hanzi": "你们好", "Pinyin": "nǐ men hǎo", "English": "hello everyone"},
    {"#": 61, "Hanzi": "中年", "Pinyin": "zhōng nián", "English": "middle-aged"},
    {"#": 62, "Hanzi": "年中", "Pinyin": "nián zhōng", "English": "mid-year"},
    {"#": 63, "Hanzi": "去年", "Pinyin": "qù nián", "English": "last year"},
    {"#": 64, "Hanzi": "年时", "Pinyin": "nián shí", "English": "during the year"},
    {"#": 65, "Hanzi": "年后", "Pinyin": "nián hòu", "English": "after a year"},
    {"#": 66, "Hanzi": "年里", "Pinyin": "nián lǐ", "English": "in the year"},
    {"#": 67, "Hanzi": "年月", "Pinyin": "nián yuè", "English": "years and months"},
    {"#": 68, "Hanzi": "后天", "Pinyin": "hòu tiān", "English": "the day after tomorrow"},
    {"#": 69, "Hanzi": "天后", "Pinyin": "tiān hòu", "English": "days later"},
    {"#": 70, "Hanzi": "年天", "Pinyin": "nián tiān", "English": "days of a year"},
    {"#": 71, "Hanzi": "年会", "Pinyin": "nián huì", "English": "annual meeting"},
    {"#": 72, "Hanzi": "年生", "Pinyin": "nián shēng", "English": "born in the year"},
    {"#": 73, "Hanzi": "人生", "Pinyin": "rén shēng", "English": "life"},
    {"#": 74, "Hanzi": "生活", "Pinyin": "shēng huó", "English": "life; living"},
    {"#": 75, "Hanzi": "出生", "Pinyin": "chū shēng", "English": "be born"},
    {"#": 76, "Hanzi": "天生", "Pinyin": "tiān shēng", "English": "innate"},
    {"#": 77, "Hanzi": "发生", "Pinyin": "fā shēng", "English": "happen"},
    {"#": 78, "Hanzi": "坐下", "Pinyin": "zuò xià", "English": "sit down"},
    {"#": 79, "Hanzi": "坐车", "Pinyin": "zuò chē", "English": "take a car"},
    {"#": 80, "Hanzi": "下车", "Pinyin": "xià chē", "English": "get off (a vehicle)"},
    {"#": 81, "Hanzi": "上车", "Pinyin": "shàng chē", "English": "get on (a vehicle)"},
    {"#": 82, "Hanzi": "不会", "Pinyin": "bù huì", "English": "cannot"},
    {"#": 83, "Hanzi": "上会", "Pinyin": "shàng huì", "English": "attend a meeting"},
    {"#": 84, "Hanzi": "上学", "Pinyin": "shàng xué", "English": "go to school"},
    {"#": 85, "Hanzi": "下学", "Pinyin": "xià xué", "English": "finish school"},
    {"#": 86, "Hanzi": "中学", "Pinyin": "zhōng xué", "English": "middle school"},
    {"#": 87, "Hanzi": "大学", "Pinyin": "dà xué", "English": "university"},
    {"#": 88, "Hanzi": "小学", "Pinyin": "xiǎo xué", "English": "primary school"},
    {"#": 89, "Hanzi": "工人", "Pinyin": "gōng rén", "English": "worker"},
    {"#": 90, "Hanzi": "大人", "Pinyin": "dà rén", "English": "adult"},
    {"#": 91, "Hanzi": "小人", "Pinyin": "xiǎo rén", "English": "child; villain"},
    {"#": 92, "Hanzi": "人学", "Pinyin": "rén xué", "English": "human study"},
    {"#": 93, "Hanzi": "过年", "Pinyin": "guò nián", "English": "celebrate the New Year"},
    {"#": 94, "Hanzi": "过去", "Pinyin": "guò qù", "English": "past; go over"},
    {"#": 95, "Hanzi": "去过", "Pinyin": "qù guò", "English": "have been"},
    {"#": 96, "Hanzi": "会不会", "Pinyin": "huì bù huì", "English": "can or not"},
    {"#": 97, "Hanzi": "能不能", "Pinyin": "néng bù néng", "English": "able or not"},
    {"#": 98, "Hanzi": "可能", "Pinyin": "kě néng", "English": "possible"},
    {"#": 99, "Hanzi": "国家", "Pinyin": "guó jiā", "English": "country"},
    {"#": 100, "Hanzi": "回来", "Pinyin": "huí lái", "English": "come back"},
    {"#": 101, "Hanzi": "回国", "Pinyin": "huí guó", "English": "return to country"},
    {"#": 102, "Hanzi": "回家", "Pinyin": "huí jiā", "English": "return home"},
    {"#": 103, "Hanzi": "行为", "Pinyin": "xíng wéi", "English": "behavior"},
    {"#": 104, "Hanzi": "火山", "Pinyin": "huǒ shān", "English": "volcano"},
    {"#": 105, "Hanzi": "开水", "Pinyin": "kāi shuǐ", "English": "boiling water"},
    {"#": 106, "Hanzi": "上面", "Pinyin": "shàng miàn", "English": "on top"},
    {"#": 107, "Hanzi": "下面", "Pinyin": "xià miàn", "English": "below"},
    {"#": 108, "Hanzi": "面子", "Pinyin": "miàn zi", "English": "face; reputation"},
    {"#": 109, "Hanzi": "东西", "Pinyin": "dōng xī", "English": "things"},
    {"#": 110, "Hanzi": "看看", "Pinyin": "kàn kàn", "English": "take a look"},
    {"#": 111, "Hanzi": "看一下", "Pinyin": "kàn yī xià", "English": "look briefly"},
    {"#": 112, "Hanzi": "只是", "Pinyin": "zhǐ shì", "English": "just; only"},
    {"#": 113, "Hanzi": "一个", "Pinyin": "yī gè", "English": "one"},
    {"#": 114, "Hanzi": "两个", "Pinyin": "liǎng gè", "English": "two"},
    {"#": 115, "Hanzi": "个人", "Pinyin": "gè rén", "English": "personal"},
    {"#": 116, "Hanzi": "学能", "Pinyin": "xué néng", "English": "learning ability"},
    {"#": 117, "Hanzi": "成人", "Pinyin": "chéng rén", "English": "adult"},
    {"#": 118, "Hanzi": "中文", "Pinyin": "zhōng wén", "English": "Chinese (language)"},
    {"#": 119, "Hanzi": "下雨", "Pinyin": "xià yǔ", "English": "raining"}
];


export default HanWords;
