# Generated by Django 4.2.6 on 2024-01-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='agreed_with_policy',
            field=models.BooleanField(default=False),
        ),
    ]
