# Generated by Django 4.2.6 on 2024-01-24 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(default='2024-01-11')),
                ('start', models.CharField(max_length=10)),
                ('finish', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=64)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_student', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=64)),
                ('slug', models.SlugField(default='Default', max_length=200, unique=True)),
                ('description', models.CharField(max_length=256)),
                ('num_of_lessons', models.IntegerField()),
                ('quiz', models.ManyToManyField(related_name='course_quiz', to='quiz_app.quiz')),
                ('student', models.ManyToManyField(related_name='course_student', to=settings.AUTH_USER_MODEL)),
                ('tutors', models.ManyToManyField(related_name='course_tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
