# Generated by Django 4.2.6 on 2024-01-29 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_roles': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'user_roles': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_as_tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
